### PR TITLE
Add promo_proto.rs

### PR DESCRIPTION
**Pull request by overvenus**
#51

Make rust-metrics cargo-compilable.

If now is not the time to add promo_proto.rs, please feel free to close this PR.

### CODE REVIEW

**Comment by posix4e** [comment]
Why not generate it in the build.rs?

**Comment by posix4e** [comment]
Can You link me to the project which uses this?

**Comment by waywardmonkeys** [comment]
I think this should've been done via a `dev-dependency` and `build.rs` and not this approach.

**Comment by posix4e** [comment]
There's an issue for that. I'm down for this in meantime. I'll fix it soon.

**Pull request merged**
