### PR TITLE
Properly tick EWMAs at the right rate.

### LINKED ISSUE #74: How are EWMA/StdMeter ticks supposed to be applied?
It seems to be implied that you're supposed to manually tick meters 12 times a minute - is that the case?

### PR DESCRIPTION
**Pull request by sfackler**
Closes #74

### CODE REVIEW

**Comment by posix4e** [comment]
Looks good to me @waywardmonkeys ?

**Comment by sfackler** [comment]
Could you cut a release with this change?

**Comment by posix4e** [comment]
Yea!

**Comment by posix4e** [comment]
release cut

**Comment by sfackler** [comment]
Thanks!

**Pull request merged**
