### PR TITLE
Create without Arc

### PR DESCRIPTION
**Pull request by chridou**
Hi,

I added some functions on the instruments to return them without wrapping them into an Arc. I use them directly so this is unecessary for me. Maybe others have that use case, too.

Cheers

Christian

### CODE REVIEW

**Comment by posix4e** [comment]
Sorry what's going on with this commit?

**Comment by chridou** [comment]
Hi!

I am using your library and I want to embed Meters into a struct. I would like to use them not wrapped into an Arc since this is some overhead for what I'm doing. I have the use case that I have to provide metrics as JSON via REST.

**Comment by posix4e** [comment]
I'm mostly ok with this, I still am having a hard time understanding the
downsides.

**Comment by chridou** [comment]
I have many meters in my struct and I was just thinking that all these Arcs are unnecessary indirections. I'm perfectly fine with using Arcs if my pull request pollutes your lib.

**Comment by waywardmonkeys** [comment]
Let me think about this overnight. I might have a different idea.

**Comment by posix4e** [comment]
@waywardmonkeys I'll give you another day :) @chridou  sorry for the delay we promise to make it better

**Comment by waywardmonkeys** [comment]
At the least, maybe `impl Default` instead of a new function `create`?

**Comment by posix4e** [comment]
Agreed but how about it at a high level?

**Comment by waywardmonkeys** [comment]
I think okay ... the use case is reasonable and this is a reasonable way to get there.

**Comment by posix4e** [comment]
Christian switch to do bruce's change and we will merge

**Comment by chridou** [comment]
Hi!

I added the Default trait instead of using a `create` function.

**Comment by waywardmonkeys** [comment]
@cdouven could you rename that to a single commit? If not, no big deal.

**Comment by waywardmonkeys** [comment]
I meant squash / rebase.

**Comment by chridou** [comment]
Whoops... i messed thinks u.. going to fix it..

**Comment by chridou** [comment]
Ok. Only 1 commit left.. Sorry for the inconvinience..

**Review by waywardmonkeys — APPROVED** [review]

**Comment by waywardmonkeys** [comment]
Thank you for your contribution and your patience!

**Comment by posix4e** [comment]
Yay

**Pull request merged**
